name: Build Android

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install dependencies
        run: npm install

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > android/app/lasbqr-release-key.jks

      - name: Verify Keystore
        run: |
          ls -la android
          ls -la android/app
          test -f android/app/lasbqr-release-key.jks && echo "Keystore exists" || echo "Keystore NOT found"

      - name: Create keystore.properties
        run: |
          cat > android/keystore.properties <<EOF
          storeFile=lasbqr-release-key.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Grant execute permission
        run: chmod +x android/gradlew

      - name: Build Release AAB
        run: |
          cd android
          pwd
          ls -la
          ls -la app
          cat keystore.properties
          ./gradlew bundleRelease --stacktrace

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: LASBQR-Release-AAB
          path: android/app/build/outputs/bundle/release/app-release.aab

      - name: Build Release APK
        run: |
              cd android
              ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
        name: LASBQR-Release-APK
        path: android/app/build/outputs/apk/release/app-release.apk
